import { NextResponse } from "next/server";
import { openai } from "@ai-sdk/openai";
import { generateText } from "ai";

// Mock responses for when API key is not available
const MOCK_RESPONSES: Record<string, string> = {
  summarize:
    "This is a mock summary of your text. In production, this would be generated by an AI model like GPT-4 or Claude. The summary would capture the main points and key information from your input, condensing it into a more digestible format while preserving the essential meaning.",
  sentiment:
    "Based on the analysis: **Positive** (85%)\n\nThe text expresses a favorable sentiment with strong positive indicators. Key emotional markers include enthusiasm, satisfaction, and optimism.",
  "text-generator":
    "Here's a creative continuation of your text:\n\nThe artificial intelligence system processed the input with remarkable efficiency, analyzing patterns and generating contextually appropriate responses. Its neural networks, trained on vast amounts of data, allowed it to understand nuances in language that would challenge even the most experienced human linguists.",
  default:
    "I understand you're asking about something interesting! In a production environment with a valid API key, I would provide a detailed, intelligent response using GPT-4 or Claude.\n\nSince this is mock mode, here's a placeholder response demonstrating the streaming capability of the AI SDK.",
};

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { prompt, mode } = body;

    // Check for API key
    const apiKey = process.env.OPENAI_API_KEY;
    const isMockMode = !apiKey || apiKey === "sk";

    if (isMockMode) {
      // Return mock response with streaming simulation
      const encoder = new TextEncoder();
      const stream = new ReadableStream({
        async start(controller) {
          const response = MOCK_RESPONSES[mode] || MOCK_RESPONSES.default;
          const chunks = response.split(" ");

          for (const chunk of chunks) {
            controller.enqueue(encoder.encode(chunk + " "));
            await new Promise((resolve) => setTimeout(resolve, 30));
          }
          controller.close();
        },
      });

      return new Response(stream, {
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Transfer-Encoding": "chunked",
        },
      });
    }

    // Real API call with OpenAI
    const systemPrompt = getSystemPrompt(mode);

    const { text } = await generateText({
      model: openai("gpt-4o"),
      system: systemPrompt,
      prompt: prompt,
    });

    // Return as streaming response
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        const chunks = text.split(" ");
        for (const chunk of chunks) {
          controller.enqueue(encoder.encode(chunk + " "));
          await new Promise((resolve) => setTimeout(resolve, 20));
        }
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Transfer-Encoding": "chunked",
      },
    });
  } catch (error) {
    console.error("AI API Error:", error);
    return NextResponse.json(
      { error: "Failed to process AI request" },
      { status: 500 }
    );
  }
}

function getSystemPrompt(mode: string): string {
  switch (mode) {
    case "summarize":
      return "You are an expert at summarizing text. Provide clear, concise summaries that capture the main points.";
    case "sentiment":
      return "You are an expert at sentiment analysis. Analyze the text and provide sentiment scores and insights.";
    case "text-generator":
      return "You are a creative writing assistant. Generate engaging, contextually appropriate text continuations.";
    default:
      return "You are a helpful AI assistant. Provide informative and accurate responses.";
  }
}
